packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  prisma: true
minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.41'
  - '@tanstack/router-core@1.171.34'
  - '@tanstack/router-generator@1.167.40'
  - '@tanstack/router-plugin@1.168.42'
  - vite@8.3.2
